<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Pages/Web.Master" Inherits="OnlineTicketSystem.Azure.Userdisp" CodeBehind="Userdisp.aspx.cs" %>

<asp:Content ID="Content1" ContentPlaceHolderID="mainContentPlaceHolder" runat="Server">

    <h3>Edit Users</h3>
    <div>

        <asp:GridView ID="usersGridView" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="usersGridView_RowCancelingEdit" OnRowDeleting="usersGridView_RowDeleting" OnRowUpdating="usersGridView_RowUpdating" AutoGenerateColumns="False" OnRowEditing="usersGridView_RowEditing" OnRowDataBound="usersGridView_RowDataBound" class="table table-striped table-condensed">
            <Columns>

                <asp:TemplateField HeaderText="UserKey">

                    <ItemTemplate>

                        <asp:Label ID="UserKeyLabel" runat="server" Text='<%#Eval("UserKey")%>'>

                        </asp:Label>
                    </ItemTemplate>

                </asp:TemplateField>

                <asp:TemplateField HeaderText="First Name">
                    <ItemTemplate>
                       <asp:Label ID="lblFirstName" runat="server"
                            Text='<%#Eval("FirstName") %>'></asp:Label>
                    </ItemTemplate> 
                    <EditItemTemplate>
                       <asp:TextBox ID="txtFirstName" runat="server"
                            Text='<%# Eval("FirstName")%>'></asp:TextBox>
                    </EditItemTemplate> 

                </asp:TemplateField>

                <asp:TemplateField HeaderText="Last Name">

                    <ItemTemplate><%#Eval("LastName") %></ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtLastName" runat="server" Text='<%#Eval("LastName")%>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="RoleKey" Visible="false">

                    <ItemTemplate><%#Eval("RoleKey") %></ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtRoleKey" runat="server" Text='<%#Eval("RoleKey")%>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField SortExpression="Role" HeaderText="Role">
                   <EditItemTemplate>
                        <asp:DropDownList ID="roleDropDown" Runat="server" 
                            DataTextField="Value" DataValueField="Key" 
                            >
                        </asp:DropDownList>        
                   </EditItemTemplate>
                   <ItemTemplate>
                       <asp:Label Runat="server" Text='<%# Eval("RoleName") %>' 
                          ID="Label1"></asp:Label>
                   </ItemTemplate>
                </asp:TemplateField>
            </Columns>

        </asp:GridView>
        <asp:Label ID="lblMsg" runat="server"></asp:Label>
    </div>



    <%--<table class="style1">
       
        <tr>
            <td>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:onlineticketConnectionString %>" 
                    SelectCommand="SELECT [Firstname], [Emailid] FROM [UserReg]" 
                    onselecting="SqlDataSource1_Selecting">
                </asp:SqlDataSource>
            </td>
            <td class="style8">
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                    DataKeyNames="Emailid" DataSourceID="SqlDataSource1" Height="246px" 
                    style="margin-top: 7px; margin-bottom: 2px" Width="304px" 
                    onselectedindexchanged="GridView1_SelectedIndexChanged">
                    <Columns>
                        <asp:BoundField DataField="Firstname" HeaderText="Firstname" 
                            SortExpression="Firstname" />
                        <asp:BoundField DataField="Emailid" HeaderText="Emailid" ReadOnly="True" 
                            SortExpression="Emailid" />
                          
                            <asp:ButtonField  ButtonType="Button" CommandName="Edit" Text="Edit User" />
                           </Columns> 
                    
                </asp:GridView>
                <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" 
                    DataSourceID="SqlDataSource2" Height="246px" style="margin-top: 12px" 
                    Width="383px">
                    <Columns>
                        <asp:BoundField DataField="TheaterName" HeaderText="TheaterName" 
                            SortExpression="TheaterName" />
                        <asp:BoundField DataField="TheaterCode" HeaderText="TheaterCode" 
                            SortExpression="TheaterCode" />
                    </Columns>
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource2" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:onlineticketConnectionString %>" 
                    onselecting="SqlDataSource2_Selecting" 
                    SelectCommand="SELECT [TheaterName], [TheaterCode] FROM [register]">
                </asp:SqlDataSource>
            </td>
            <td>
            </td>
        </tr>
        
    </table>--%>
</asp:Content>
